### ISSUE TITLE
there exists a number of bugs in \qlib\scripts\data_collector\cn_index\collector.py

### ISSUE THREAD

**Issue by FluidDoctor** [microsoft/qlib#1065]
there exists a number of bugs in \qlib\scripts\data_collector\cn_index\collector.py
1. line 333, it shoulde be "class CSI100Index", not now "class CSI100" AND in line 344, it shoulde be "return 1".  after make these changes, run python collector.py --index_name CSI100 --qlib_dir ~/.qlib/qlib_data/cn_data --method parse_instruments will give a correct response.
2. line 330, it shoulde be "return 0", not now "return 1". "return 1" can give a results but not correct. after make this change, can not work ,will raise error like this "scripts\data_collector\cn_index\collector.py", line 160, in normalize_symbol
    symbol = f"{int(symbol):06}"
ValueError: cannot convert float NaN to integer"
I have tried to fix this bug, but unlikely, unsuccess.

**Comment by SunsetWolf** [comment]
I am glad to receive your very organized questions.
1. The class name of csi100 has been fixed in [PR 1046](https://github.com/microsoft/qlib/pull/1046).
The return value of the html_table_index method in the CSI100Index class has been fixed in [PR 1070](https://github.com/microsoft/qlib/pull/1070).
2. The return value of the html_table_index method in the CSI300Index class has been fixed in [PR 1070](https://github.com/microsoft/qlib/pull/1070).
`ValueError: cannot convert float NaN to integer` has been fixed in [PR 1046](https://github.com/microsoft/qlib/pull/1046).
I hope my reply can help you, thanks!
