### ISSUE TITLE
some doubts for all stocks features and cross-sectional features and nn streaming 

### ISSUE THREAD

**Issue by gucasbrg** [microsoft/qlib#1133]
1. taking A shares as an example, calculate features for all stocks . Is there a relatively simple configuration plan?
2. As you know, cross-sectional features are very important. are there apis to calculate  cross-sectional features on the same day?
3. Some nn models are basically processed by streaming. As mentioned above, if the amount of data is particularly large, it is not suitable to put it all in memory. how to deal with this problem
maybe store training data in disk?

**Comment by you-n-g** [comment]
Hi，@gucasbrg
1. Do you think [this example ](https://github.com/microsoft/qlib/blob/main/examples/benchmarks/LightGBM/workflow_config_lightgbm_configurable_dataset.yaml#L15) is relative simpler?  What will a simple configuration plan be like? Can you give us any advice?
2. Currently, cross-sectional operations are done by [processors](https://github.com/microsoft/qlib/blob/main/examples/benchmarks/LightGBM/workflow_config_lightgbm_configurable_dataset.yaml#L24)
3. Currently, there are no ready-made implementations. By design, such requirements are expected implemented as a specific handler.


Thanks
