### ISSUE TITLE
source data lose precise after dump

### ISSUE THREAD

**Issue by lerit** [microsoft/qlib#1272]
**souce data:**
```
date,open,close,high,low,volume,change,turnover
2000-01-04,600000.41,600000.42,600000.43,600000.44,600000.45,600000.46,600000.47
2000-01-05,600000.51,600000.52,600000.53,600000.55,600000.55,600000.56,600000.57
2000-01-06,600000.61,600000.62,600000.63,600000.66,600000.66,600000.66,600000.67
```
**dump result(dump_all and print features):**
![image](https://user-images.githubusercontent.com/4743467/187246277-4492e3a1-3c53-4516-950f-ff3eebff6c90.png)

source data changed after dump,by source code:
```
np.array(_df[field]).astype("<f").tofile(fp)
```

it change float64 to little-endian single-precision float,but why do so?

**Comment by Chaoyingz** [comment]
It should be a display bug, you can index to a single variable to see the value.

**Comment by lerit** [comment]
@Chaoyingz  Thank you for your reply.
part of it.when i show value in vscode,i get another value(`df.iloc[0:1, [0]]`):
![image](https://user-images.githubusercontent.com/4743467/187568947-9ab8f744-10fd-4f8e-9c78-fca1066110b0.png)
and i try to save result to csv,to see the value:
![image](https://user-images.githubusercontent.com/4743467/187566168-445661cf-f90a-42b8-81eb-efe0d59dba70.png)

crazy me:
source value:600000.41
dump and print value:600000.4375
dump and save csv value:600000.44

**which one i can trust?**

**Comment by SunsetWolf** [comment]
This is because the precision in the dump process is float32, which causes the precision to be lost, you can try to change this precision [in the dump_bin file](https://github.com/microsoft/qlib/blob/main/scripts/dump_bin.py#L237).
However, the precision is also lost when using D.features, change the precision limit in [file_storage.start_index](https://github.com/microsoft/qlib/blob/main/qlib/data/storage/file_storage.py#L334) and [file_storage.\_\_getitem\_\_](https://github.com/microsoft/qlib/blob/main/qlib/data/storage/file_storage.py#L348) and [data.expression](https://github.com/microsoft/qlib/blob/main/qlib/data/data.py#L869) to solve this problem.
It is possible to place constraints on precision in the config file, which gives the user the flexibility to modify it, If you are interested in this, you can submit your changes.
