### ISSUE TITLE
Is trained_model same as trained_model.pkl ?

### ISSUE THREAD

**Issue by quantcn** [microsoft/qlib#1282]
When we use
R.save_objects(trained_model=model)
It generates a file "trained_model ",  I wonder if this is a pkl file， same as trained_model.pkl?

**Comment by SunsetWolf** [comment]
As you mentioned, if you use `R.save_objects(trained_model=model)` method to save objects, it will generate `train_model` file, and you can also try to use `R.save_objects(**{"train_model.pkl": model})` method to save objects, it will generate `train_model.pkl` file.

**Comment by you-n-g** [comment]
@quantcn 
R.save_objects provides well-decoupled model management features.
The trained_model is simply the filename in the storage. 

If other components depend on the filename saved on the storage (e.g.  https://github.com/microsoft/qlib/blob/main/qlib/workflow/online/update.py#L63) , they will be affected.
Otherwise, any name will be valid.
