### ISSUE TITLE
Cannot reproduce results of DDG-DA

### ISSUE THREAD

**Issue by MogicianXD** [microsoft/qlib#1383]
I run the orginal codes by `python workflow.py run_all` but the metrics are lower than those reported in `examples/benchmark_dynamic/README.md`

| Model Name       | Dataset | IC | ICIR | Rank IC | Rank ICIR | Annualized Return | Information Ratio | Max Drawdown |
|------------------|---------|----|------|---------|-----------|-------------------|-------------------|--------------|
| RR[Linear]       |Alpha158 |0.088|0.570|0.102    |0.622      |0.077              |1.175              |-0.086        |
| DDG-DA[Linear]   |Alpha158 |0.093|0.622|0.106    |0.670      |0.085              |1.213              |-0.093        |
| Reproduced   |Alpha158 |0.084 |0.564|0.097    |0.611      |0.048              |0.688              |-0.107        |

I make sure I make no revision. Could you check the published codes?

The log shows that the IC metric is almost consistently decreasing for more epochs.

Timestamp IC epoch_number
1670210565192 0.08099887254773068 0
1670210581303 0.08101838958077529 1
1670210598426 0.08100647604512182 2
1670210613297 0.080930365578167 3
1670210627714 0.08089647731047853 4
1670210641211 0.08082790339120408 5
1670210655006 0.080754516160323 6
1670210668283 0.08059993567441397 7
1670210684522 0.08049239664882533 8
1670210699828 0.08034700421487219 9
1670210714386 0.08021271128788895 10
1670210728971 0.0800196928987357 11
1670210744130 0.07986316091534788 12
1670210758226 0.07971055623825253 13
1670210772044 0.07953790860281054 14
1670210784364 0.07935235736630272 15
1670210796546 0.07919402866530238 16
1670210810438 0.07899181643972905 17
1670210822736 0.0788395168440115 18
1670210834912 0.07868853916701157 19
1670210847879 0.07852273198291998 20
1670210861767 0.07838506480676588 21
1670210876507 0.07823007225828875 22
1670210889186 0.07806567279551518 23
1670210903050 0.07788316799007546 24
1670210917431 0.07773608713606715 25
1670210931164 0.07757866654522687 26
1670210944477 0.07745913291145204 27
1670210957743 0.07733839759749703 28
1670210971870 0.07721419436871192 29
1670210985728 0.07708123063589128 30
1670210999387 0.076959251039629 31
1670211013695 0.07682221256817962 32

**Comment by al33m501** [comment]
Did you run it multiple times with different random state? I assume that authors publish average results of multiple runs.

**Comment by MogicianXD** [comment]
I also run 10 times with random seed from 43 to 52. Still not good. The results are:
'IC': [0.0806367201269977,
        0.08404688359457639,
        0.08451167437750381,
        0.08228024116262979,
        0.08424628933506924,
        0.08256571737751087,
        0.08332169847379733,
        0.08205690860402721,
        0.08399074425431431,
        0.08368972384223124],
 'ICIR': [0.5340935645513984,
          0.5594536918961193,
          0.5551282662211535,
          0.5386204215095555,
          0.5541857984348951,
          0.546141531144539,
          0.5477635852316844,
          0.5393459131431579,
          0.5562508737442103,
          0.5520930309263579],
 'Rank IC': [0.09356072878406832,
             0.09766646482080422,
             0.09775931396801546,
             0.09504670362710686,
             0.09700311508785632,
             0.09467931967333201,
             0.09657094821039207,
             0.09552488774777246,
             0.09640712795821968,
             0.09563137695443545],
 'Rank ICIR': [0.5818655127103171,
               0.6102156480341566,
               0.6014391584345745,
               0.5831324608959063,
               0.5960567563650023,
               0.5830372302553581,
               0.5944706299725373,
               0.5895853420382431,
               0.5944235566487662,
               0.5874199361647343]}

**Comment by wendili-cs** [comment]
Hello, thank you for your report. We experimented and found that if we use the default Yahoo Finance to generate the Alpha158 dataset, the problem does happen. This is because the Qlib data collected from Yahoo Finance does not contain `VWAP`, so all related factors are missing and will be filled with 0. It leads to a rank-deficient matrix (a matrix does not have full rank). DDG-DA uses a [closed-form solution](https://github.com/microsoft/qlib/blob/main/qlib/contrib/meta/data_selection/net.py#L62) to calculate the lower-level proxy model. A rank-deficient matrix prevents lower-level DDG-DA optimization from being solved. We generated the Alpha158 dataset from our internal data source so we did not suffer from this problem. Moreover, Yahoo Finance's data quality is not very high, we tried to remove all-zero columns but the performance is still not good (for example there are missing trading days). 

The solution is to switch the source data that generates the Alpha158 dataset. For example, you can use [crowded-sourced data](https://github.com/microsoft/qlib/tree/main/scripts#use-crowd-sourced-data) that has higher quality. I have updated the results of the crowded-sourced data source on the [experiment table](https://github.com/microsoft/qlib/blob/main/examples/benchmarks_dynamic/README.md).

**Comment by MogicianXD** [comment]
Thanks for your kind answer!

**Comment by MogicianXD** [comment]
Thanks for your kind answer!

**Comment by lianlin666** [comment]
> I also run 10 times with random seed from 43 to 52. Still not good. The results are: 'IC': [0.0806367201269977, 0.08404688359457639, 0.08451167437750381, 0.08228024116262979, 0.08424628933506924, 0.08256571737751087, 0.08332169847379733, 0.08205690860402721, 0.08399074425431431, 0.08368972384223124], 'ICIR': [0.5340935645513984, 0.5594536918961193, 0.5551282662211535, 0.5386204215095555, 0.5541857984348951, 0.546141531144539, 0.5477635852316844, 0.5393459131431579, 0.5562508737442103, 0.5520930309263579], 'Rank IC': [0.09356072878406832, 0.09766646482080422, 0.09775931396801546, 0.09504670362710686, 0.09700311508785632, 0.09467931967333201, 0.09657094821039207, 0.09552488774777246, 0.09640712795821968, 0.09563137695443545], 'Rank ICIR': [0.5818655127103171, 0.6102156480341566, 0.6014391584345745, 0.5831324608959063, 0.5960567563650023, 0.5830372302553581, 0.5944706299725373, 0.5895853420382431, 0.5944235566487662, 0.5874199361647343]}

My result is similar with you, so how did you use the crowded resource data to improve the result? I did not find the right method to process new data and use it.
