### ISSUE TITLE
Alpha158 Label Calculation (Why use close price 2 days from now?)

### ISSUE THREAD

**Issue by reveching** [microsoft/qlib#1514]
## ❓ Questions and Help

I noticed that when calculating label for Alpha158: 

def get_label_config(self):
        return ["Ref($close, -2)/Ref($close, -1) - 1"], ["LABEL0"]

Why do we predict the price change after market closes Tomorrow? Isn't that saying we're ignoring tomorrow's trade?

**Comment by Fivele-Li** [comment]
The approach of qlib is to predict the price increase of t2 compared to t1 based on all available information at t0, and then make decisions for t1 based on this prediction. 
This is because the trading rules in the Chinese A-share market follow a T+1 rule, meaning that stocks purchased on the first day can only be sold on the second day. 
Therefore, after obtaining today's closed data, we can only determine tomorrow's actions by predicting the price increase of the day after tomorrow compared to tomorrow.

**Comment by reveching** [comment]
I mean in this case you take action at the close price of tomorrow, meaning that you skip the whole trade from 9:30 AM to 14:59 PM. You can definitely take action at the open price, like: "Ref($open, -2)/Ref($open, -1) - 1".

**Comment by reveching** [comment]
Prediction power fades out over time so you definitely don't want to place orders at the end of T1.

**Comment by Fivele-Li** [comment]
I think it's possible to set the label using the method you mentioned, `Ref($open, -2)/Ref($open, -1) - 1`. Qlib may be using `Ref($close, -2)/Ref($close, -1) - 1` by chance or out of habit.

**Comment by reveching** [comment]
Yes. We can also set backtest deal price to 'open' and I'm seeing IC improved by quite a lot. Something like 0.04 -> 0.07, so yea
