### ISSUE TITLE
when will it have a python3.9 supported version?

### ISSUE THREAD

**Issue by JesseLT** [microsoft/qlib#156]
I'm using Macbook air m1. As far as I kown,only py39 work well on it!

**Comment by you-n-g** [comment]
We don't support Python 3.9 because statsmodels  doesn't support  Python 3.9.
We will support  Python 3.9 if we find replacement for statsmodels.

If you don't use  [statsmodels](https://github.com/microsoft/qlib/blob/4f61d43d148faa5b8892241463ef3a0a3ae3a9da/qlib/contrib/report/analysis_model/analysis_model_performance.py#L9),  you can remove [this line](https://github.com/microsoft/qlib/blob/4f61d43d148faa5b8892241463ef3a0a3ae3a9da/setup.py#L47) and use Python 3.9

**Comment by Derek-Wds** [comment]
In add to `statsmodels`, `matplotlib` also doesn't support Python 3.9. Please pay attention to that if you want to plot something.

**Comment by JesseLT** [comment]
> In add to `statsmodels`, `matplotlib` also doesn't support Python 3.9. Please pay attention to that if you want to plot something.

 `statsmodels`, `matplotlib`  have supported Python 3.9! I have installed them with `pip`.    0.0

**Comment by you-n-g** [comment]
@JesseLT  
Can you run qlib successfully on Python 3.9 now?

**Comment by JesseLT** [comment]
> @JesseLT
> Can you run qlib successfully on Python 3.9 now?

unfortunately！Nope!
