### ISSUE TITLE
How to calculate SMA using Operator Expression

### ISSUE THREAD

**Issue by davidwang0606** [microsoft/qlib#173]
## ❓ Questions and Help
 IF Y=SMA(X,N,M) ， Y=(M*X+(N-M)*Y')/N  Y‘ is the last value of Y.  
How to express SMA($close, 6,  1) using Operator Expression? Thanks

**Comment by bxdd** [comment]
@davidwang0606  hi, I think ``SMA`` can be represented by ``EMA``:

* According to the ``Recurrence Formula`` of ``SMA``: ![1](https://latex.codecogs.com/svg.latex?SMA_{N,M}(x_n)=\frac{Mx_n+(N-M)SMA_{N,M}(x_{n-1})}{N}), its ``General Formula`` is ![2](https://latex.codecogs.com/svg.latex?SMA_{N,M}(x_n)=\frac{M}{N}\sum_{k=0}^{\inf}(\frac{N-M}{N})^{k}x_{n-k},%20x_0=x_{-1}=...=x_{-\inf}=x_1)
* The ``General Formula`` of ``SMA`` is ![3](https://latex.codecogs.com/svg.latex?EMA_{K}(x_n)=\frac{2}{K+1}\sum_{k=0}^{\inf}(\frac{K-1}{K+1})^{k}x_{n-k},%20x_0=x_{-1}=...=x_{-\inf}=x_1)
* It is easy to find that when ![4](https://latex.codecogs.com/svg.latex?\frac{N-M}{N}=\frac{K-1}{K+1}), that is ![5](https://latex.codecogs.com/svg.latex?K=\frac{2N-M}{M}), the following formula holds: ![6](https://latex.codecogs.com/svg.latex?EMA_{K}(x_n)=\frac{2}{K+1}\sum_{k=0}^{\inf}(\frac{K-1}{K+1})^{k}x_{n-k}=\frac{2}{2N/%20M}\sum_{k=0}^{\inf}(\frac{2N-2M}{2N})^{k}x_{n-k}=\frac{M}{N}\sum_{k=0}^{\inf}(\frac{N-M}{N})^{k}x_{n-k}=SMA_{N,M}(x_n))
* So, **you can express **SMA($close, 6, 1)** by Operator Expression`EMA($close, 11)`**.
* **PS**: Currently, Qlib does not support EMA operations with non-integer parameters, so when (2N-M)/N is non-integer, SMA It can only be approximated by EMA. Fortunately, SMA($close, 6, 1) can be fully represented by EMA because (2*6-1)/1 is an integer. 
* By the way, In the near future, Qlib will support the registration of custom operators. You can implement a **dedicated operator** to calculate SMA more clearly and easily, refer to #92.

**Comment by davidwang0606** [comment]
Got it ! Thanks

**Comment by bxdd** [comment]
URW
