### ISSUE TITLE
ValueError: unknown metric `mse`

### ISSUE THREAD

**Issue by Hosen760** [microsoft/qlib#1780]
## ❓ Questions and Help

We sincerely suggest you to carefully read the [documentation](http://qlib.readthedocs.io/) of our library as well as the official [paper](https://arxiv.org/abs/2009.11189). After that, if you still feel puzzled, please describe the question clearly under this issue.
![image](https://github.com/microsoft/qlib/assets/135490367/b23bd0c8-a580-4265-831d-4453df461a20)
![image](https://github.com/microsoft/qlib/assets/135490367/53ea3f48-f722-42f3-91fd-d228188c7c06)

**Comment by raikiriww** [comment]
From the stack trace you provided, it seems the error is due to the unknown metric 'mse' specified in your code. According to the error message, the acceptable metrics are an empty string '' or 'loss'. You can resolve this issue by changing metric='mse' to either metric='' or metric='loss'. This should make the model use the default loss function as the metric, rather than looking for a metric named 'mse', which is not recognized.

Hope this helps!

**Comment by you-n-g** [comment]
Solved and  Merged
