### ISSUE TITLE
how to print the sell_order_list & buy_order_list of next trading day?

### ISSUE THREAD

**Issue by quinnnnnnnnn** [microsoft/qlib#215]
## ❓ Questions and Help

At present, I choose what to buy and sell in the next trading day based on the score of the most recent trading day.
How do I print out the strategy generated sell_order_list & buy_order_list of next trading day?

**Comment by you-n-g** [comment]
Currently, the trading strategies need to interact with the [exchange](https://github.com/microsoft/qlib/blob/main/qlib/contrib/strategy/strategy.py#L352) to generate orders
If you want to get the orders in the next trading day,  you have to implement some interfaces of exchange in the next trading day.

The following data on trading day will be required
- adjust factors
- expected trading price (to decide the amount of the order)
- is the stock tradable

We didn't provide any examples because the public data sources don't privde such data.

**Comment by quinnnnnnnnn** [comment]
Thanks for your explanation. But I got another question 0v0，  if this(👇) problem hapend
https://github.com/microsoft/qlib/issues/204#issue-790737283
Such us buy or sell numbers was not as expect，How to maintain a position of 50 stocks？
Should I buy (or sell) the next-ranked stocks according to the score or take some other measures🤔

**Comment by you-n-g** [comment]
@quinnnnnnnnn 
You can make the strategy only consider transaction on tradable stocks 
https://github.com/microsoft/qlib/blob/main/qlib/contrib/strategy/strategy.py#L223
