### ISSUE TITLE
ConfigDataHandler and QLibDataHandler mentiond in <Data Layer: Data Framework & Usage> cannot be found

### ISSUE THREAD

**Issue by ke-fan** [microsoft/qlib#344]
## 📖  [Data Layer: Data Framework & Usage](https://qlib.readthedocs.io/en/latest/component/data.html#id7)

In Document: https://qlib.readthedocs.io/en/latest/component/data.html#id7，it says:

If users want to load features and labels by config, users can inherit qlib.data.dataset.handler.ConfigDataHandler, Qlib also provides some preprocess method in this subclass.

If users want to use qlib data, QLibDataHandler is recommended. Users can inherit their custom class from QLibDataHandler, which is also a subclass of ConfigDataHandler.

But i cannot find these two classes: qlib.data.dataset.handler.ConfigDataHandler and QLibDataHandler

**Comment by bxdd** [comment]
@ke-fan Hi, due to the version update, this part of the document is no longer valid. I will fix the document soon.
In the new version, if you want to load features and labels by config, you can define a `new handler` that inherits `qlib.contrib.data.handler.Alpha158`[link](https://github.com/microsoft/qlib/blob/main/qlib/contrib/data/handler.py#L185). Also, you can pass `qlib.contrib.data.processor.ConfigSectionProcessor`[link](https://github.com/microsoft/qlib/blob/main/qlib/contrib/data/processor.py#L10) that provides some preprocess method into the `new handler`.
