### ISSUE TITLE
Related source code showing high performance infrastructure

### ISSUE THREAD

**Issue by Yolanflower** [microsoft/qlib#392]
## ❓ Questions and Help

I want to know how does qlib realize high performance when calculating alpha or implementing strategies, i.e. why does qlib cost less time that the other data structures. It would be grate if you could show the related source code for that.

**Comment by Derek-Wds** [comment]
Hi, all the codes are listed in this repo. If you want to have a broad idea of how qlib works, then you could take a look at our [paper](https://arxiv.org/abs/2009.11189). Hope it helps~

**Comment by Yolanflower** [comment]
Thanks a lot! And could you please show a example code about how qlib load the data to make the whole process faster?

**Comment by you-n-g** [comment]
@Yolanflower  Sorry, these code are not released yet(We tested on multiple storage in a complicated environment.  Because there are lots of more important issues.  It's hard to spare time to clean up them ).  
You can load the same data from other storage (for example some database or file) amd dp the same computation, you can compare the performance difference.
