### ISSUE TITLE
ValueError: instruments not exists for market csi500

### ISSUE THREAD

**Issue by pan-cai** [microsoft/qlib#52]
```
instruments = D.instruments(market='csi500')
D.list_instruments(instruments=instruments, start_time='2015-01-01', end_time='2016-02-15', as_list=True)
```
```
xxx/qlib/data/data.py in _load_instruments(self, market)
    574         fname = self._uri_inst.format(market)
    575         if not os.path.exists(fname):
--> 576             raise ValueError("instruments not exists for market " + market)
    577         _instruments = dict()
    578         with open(fname) as f:

ValueError: instruments not exists for market csi500
```
----
**xxx/scripts/data_collector/csi/collector.py**
No CSI500 and other market

**Comment by you-n-g** [comment]
@pan-cai 
Due to the licence problems, we can only use public and free data on the internet.(Only csi300 is available on the internet now.)

If you have public data resource, please notify us.  We'll enrich our dataset.
If you have private data source, you follow our scripts to convert the data to qlib format.

**Comment by pan-cai** [comment]
Ok, thanks
