### ISSUE TITLE
some features calculated as -inf on my data

### ISSUE THREAD

**Issue by kurucan** [microsoft/qlib#666]
some features are -inf, on my data how to check and drop those columns before training the model or exclude some features in the first place? Should I define a new alpha class for my data?

![inf](https://user-images.githubusercontent.com/7413036/139559613-7e953b42-3676-4b9b-abbe-40bb445530aa.jpg)

and, how to troubleshoot those -inf values?

**Comment by you-n-g** [comment]
@kurucan 
Here is the detailed expression of these features
https://github.com/microsoft/qlib/blob/main/qlib/contrib/data/handler.py#L221
For  KLOW,  please check the open price.
Maybe it is caused by dividing zeros.


If you want to drop it, you can use  the [DropCol](https://github.com/microsoft/qlib/blob/main/qlib/data/dataset/processor.py#L116) processor
