### ISSUE TITLE
How to view or export everyday's order and holding?

### ISSUE THREAD

**Issue by hhr8** [microsoft/qlib#722]
## ❓ Questions and Help

How to view or export everyday's equity holding and order list? BTW, it seems that time period of data in qlib only cover till 2021-06-11, then how can I know what I should buy tomorrow? Should I use outside data like Jqdata or something?

**Comment by you-n-g** [comment]
@hhr8  
After you follow @zhupr's step to daily update your data(Of course you can use other data sources with higher quality)

You can follow this script to serve your model to generate prediction daily
https://github.com/microsoft/qlib/blob/main/examples/online_srv/update_online_pred.py

Because converting the model signal to orders the next day in the future requires more data (the price adjusting factor tomorrow), we don't have off-the-shelf scripts to help you convert your model predictions to orders.

**Comment by kurucan** [comment]
@zhupr many thanks, I can see the order list with verbose:true, how to record order_list or export the order list as df?

**Comment by kurucan** [comment]
I see the output below when I print the positions_normal_df
<img width="549" alt="image" src="https://user-images.githubusercontent.com/7413036/144726698-6af8cf86-9ce0-471e-aaf2-d0eb2b9ee431.png">

**Comment by zhupr** [comment]
> I see the output below when I print the positions_normal_df <img alt="image" width="549" src="https://user-images.githubusercontent.com/7413036/144726698-6af8cf86-9ce0-471e-aaf2-d0eb2b9ee431.png">

fixed: https://github.com/microsoft/qlib/pull/719 https://github.com/microsoft/qlib/pull/719/commits/6ecf9db9c3c973e7f5348ba84ea8e28268ea2288

**Comment by hhr8** [comment]
@zhupr @you-n-g many thanks! I can see the order after following your guidance.
