### ISSUE TITLE
Online serving is not online learning?

### ISSUE THREAD

**Issue by Wendroff** [microsoft/qlib#769]
## ❓ Questions and Help

I find there is a part named "Online Serving" in the doc. And I thought it's a kind of online learning in which models can be imporved with historical data growing. However, I read the example and found that those models still are trained separetly. Am I tight? Is it possible to implement online learing under qlib's framework?

**Comment by you-n-g** [comment]
The online serving module is designed for serving online models instead of online learning.

But you can try to improve further to accommodate online learning (Maybe it may take some effort)

You can refer to this example:
https://github.com/microsoft/qlib/blob/main/examples/online_srv/online_management_simulate.py#L65

The  RollingStrategy behaves like an online learning algorithm.
It updates the model periodically.
