### ISSUE TITLE
empty dataset error for benchmark dynamics using gbdt meta

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [microsoft/qlib#883]
## 🐛 Bug Description
When changing the workflow yaml to most recent (2021-06-10 for test data), and using `--sim_task_model="gbdt"`, reports this data empty error:
`raise ValueError("Empty data from dataset, please check your dataset config.")`

## To Reproduce

1. change workflow yaml to the following workflow yaml (only thing changed is the end date of the qlib data). [workflow_config_lightgbm_Alpha158.txt](https://github.com/microsoft/qlib/files/7919201/workflow_config_lightgbm_Alpha158.txt)

2.  `python workflow.py --forecast_model="gbdt" --sim_task_model="gbdt" run_all`

## Environment
```
Linux
x86_64
Linux-4.18.0-147.el8.x86_64-x86_64-with-glibc2.2.5
#1 SMP Wed Dec 4 21:51:45 UTC 2019

Python version: 3.8.6 (default, Oct 22 2020, 17:03:03)  [GCC 9.3.0]

Qlib version: 0.8.3.99
numpy==1.22.1
pandas==1.3.5
scipy==1.7.3
requests==2.27.1
sacred==0.8.2
python-socketio==5.5.1
redis==4.1.1
python-redis-lock==3.7.0
schedule==1.1.0
cvxpy==1.1.18
hyperopt==0.1.2
fire==0.4.0
statsmodels==0.13.1
xlrd==2.0.1
plotly==5.5.0
matplotlib==3.5.1
tables==3.7.0
pyyaml==5.4.1
mlflow==1.23.0
tqdm==4.62.3
loguru==0.5.3
lightgbm==3.3.2
tornado==6.1
joblib==1.1.0
fire==0.4.0
ruamel.yaml==0.17.20
```
## Additional Notes
output attatched
[debug.txt](https://github.com/microsoft/qlib/files/7919204/debug.txt)

**Comment by you-n-g** [comment]
@wendili-cs  will help to answer this question.

**Comment by wendili-cs** [comment]
There are two reasons that may cause this problem. 
The first reason is using cache in `rolling_benchmark.py` (https://github.com/microsoft/qlib/blob/main/examples/benchmarks_dynamic/baseline/rolling_benchmark.py#L55). The code will pickle the handler for future use, now it does not check whether the data is up-to-date, so deleting the `pkl` file in the `baseline` folder will solve this problem. 
The second reason is the horizon setting. Currently, the default forecasting horizon of `rolling_benchmark.py` is 20 trading days (https://github.com/microsoft/qlib/blob/main/examples/benchmarks_dynamic/baseline/rolling_benchmark.py#L50). If you want to calculate the label on time `t`, you need data 20 trading days later on time `t`, because you need 20 more future data. If the latest available data with 1 horizon day is 2021-06-10, the latest available data with 20 horizon days is 20 trading days earlier, so it should be set to 2021-05-17 in this case.
