### ISSUE TITLE
What are the meanings of metrics of benchmarks performance? Why is Sharpe Ratio not included in the metrics?

### ISSUE THREAD

**Issue by Waterkin** [microsoft/qlib#919]
## ❓ Questions and Help

We sincerely suggest you to carefully read the [documentation](http://qlib.readthedocs.io/) of our library as well as the official [paper](https://arxiv.org/abs/2009.11189). After that, if you still feel puzzled, please describe the question clearly under this issue.

**Comment by you-n-g** [comment]
> What are the meanings of metrics of benchmarks performance?
- Can [this PR](https://github.com/microsoft/qlib/pull/920) answer your question? 


> Why is Sharpe Ratio not included in the metrics?
-  [Sharp Ratio ](https://www.investopedia.com/terms/s/sharperatio.asp) and [Information ratio ](https://www.investopedia.com/terms/i/informationratio.asp) are both evaluation metrics which consider both return and risk.
   -  Sharp Ratio is compared to risk-free return.  Information ratio is compared to **a specific benchmark**. In our forecasting tasks, the model are predicting the excess return of stocks to CSI300 instead of risk-free return.  So information ratio is a more reasonable metric.

**Comment by Waterkin** [comment]
Thanks for your reply, young.
