### ISSUE TITLE
question about online_management_simulate  

### ISSUE THREAD

**Issue by louis-xuy** [microsoft/qlib#954]
when i run online_management_simulate code of examples i found that the start_time and end_time is different with segments train date

is anything wang?

![image](https://user-images.githubusercontent.com/8952852/157056522-03f26c44-937b-41ca-afc0-bd65f5f2cec1.png)

**Comment by SunsetWolf** [comment]
Glad to receive your issue, the reason for this problem: qlib has multiple layers, where the datahandler layer is responsible for fetching data, and the dataset layer is responsible for doing time division on the data fetched by the datahandler, the dataset layer and the datahandler layer are independent of each other, so your problem is normal for the current qlib, and there is no mechanism to make them exactly the same.

**Comment by louis-xuy** [comment]
> Glad to receive your issue, the reason for this problem: qlib has multiple layers, where the datahandler layer is responsible for fetching data, and the dataset layer is responsible for doing time division on the data fetched by the datahandler, the dataset layer and the datahandler layer are independent of each other, so your problem is normal for the current qlib, and there is no mechanism to make them exactly the same.

As you said, the datahandler layer gets the data and passes it to the dataset layer, but the time range of the data obtained by the datahandlerlayer does not match the time range of the data required by the datasetlayer, will there be no problem?

**Comment by SunsetWolf** [comment]
> As you said, the datahandler layer gets the data and passes it to the dataset layer, but the time range of the data obtained by the datahandlerlayer does not match the time range of the data required by the datasetlayer, will there be no problem?

The datahandler layer will fetch more data, but the extra data will not have any effect (If the datahandler layer gets less data, it will cause problems).
